batch_size: 1
beta1: 0.9
beta2: 0.999
data: phantom
encoder:
  coordinates_size: 2
  embedding: gauss
  embedding_size: 256
  scale: 4
img_path: /data/bowen/SparseReconstruction/lidc_gt/img99.npy
img_size: 256
log_iter: 10
loss: L2
lr: 1.0e-05
max_iter: 1000
model: SIREN
net:
  network_depth: 8
  network_input_size: 512
  network_output_size: 1
  network_width: 256
num_projs: 25
optimizer: Adam
pretrain_model_path: /data/bowen/SparseReconstruction/3d-ct-full-dose/models/phantomproj25robust_lidc99/checkpoints/model_001000.pt
prior_index: 99
recon_name: /data/bowen/SparseReconstruction/3d-ct-full-dose/lidc/PINER_recon/recon_99_robust.npy
reg: None
val_iter: 100
weight_decay: 0.0
