batch_size: 1
beta1: 0.9
beta2: 0.999
data: phantom
encoder:
  coordinates_size: 2
  embedding: gauss
  embedding_size: 256
  scale: 4
img_path: square_test.npy
img_size: 256
log_iter: 10
loss: L2
lr: 0.0001
max_iter: 2000
model: SIREN
net:
  network_depth: 8
  network_input_size: 512
  network_output_size: 1
  network_width: 256
num_proj: 25
optimizer: Adam
pretrain_model_path: /data/bowen/SparseReconstruction/3d-ct-full-dose/models/phantomproj25img5brain/checkpoints/model_001000.pt
recon_name: square_test_recon_lasso.npy
reg: lasso
val_iter: 100
weight_decay: 0.0
