batch_size: 1
beta1: 0.9
beta2: 0.999
body_part: abdominal
data: phantom
encoder:
  coordinates_size: 2
  embedding: gauss
  embedding_size: 256
  scale: 8
img_index: 49
img_path: notebooks/001.npy
img_size: 256
log_iter: 10
loss: L2
lr: 0.0001
max_iter: 200
model: SIREN
net:
  network_depth: 8
  network_input_size: 512
  network_output_size: 1
  network_width: 256
num_projs: 50
optimizer: Adam
recon_path: c11_sinogram_denoised.npy
val_iter: 100
weight_decay: 0.0001
